version: 2

defaults: &defaults
  working_directory: ~/app
  resource_class: small
  docker:
    - image: cimg/node:21.4.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{ .Branch }}
            - yarn-v1
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          key: yarn-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - .yarn/cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            yarn dedupe -c
            yarn lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  maybe_deploy:
    # Tag filtering in CircleCI is unreliable - this is hacky, but it works
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
            npm publish --scope=@markormesher --access public

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - maybe_deploy:
          requires:
            - lint
            - build
